"""
Django development settings for project project.

Generated by 'django-admin startproject' using Django 3.0.11.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

from .shared import *  # pylint: disable=W0614,W0401

# Enabling debug mode
DEBUG = True
