"""
Django production settings for project project.

Generated by 'django-admin startproject' using Django 3.0.11.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

# import logging.config

from .shared import *  # pylint: disable=W0614,W0401

# SameSite Cookies
# https://stackoverflow.com/questions/63576338/django-check-cookiess-samesite-attribute
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SAMESITE = "None"
